import { useNavigate } from "react-router-dom";

const Missions = () => {
    const navigate = useNavigate() 
    return(
        <div className='info-dump2'>
            <h1>First Mission</h1>
            <p>We human beings have been venturing into space since October 4, 1957, when the Union of Soviet Socialist Republics (U.S.S.R.) launched Sputnik, the first artificial satellite to orbit Earth. This happened during the period of political hostility between the Soviet Union and the United States known as the Cold War.</p>
            <h1>First Man Mission</h1>
            <p>On April 12, 1961, aboard the spacecraft Vostok 1, Soviet cosmonaut Yuri Alekseyevich Gagarin becomes the first human being to travel into space. During the flight, the 27-year-old test pilot and industrial technician also became the first man to orbit the planet, a feat accomplished by his space capsule in 89 minutes.</p>
            <h1>Accidents and Disasters in Spaceflight History</h1>
            <h2>STS-51-L: Space Shuttle Challenger Disaster</h2>
            <p>The space shuttle Challenger disaster that occurred on January 28, 1986, marked one of the most devastating days in the history of space exploration. Just over a minute after the space shuttle lifted off, a malfunction in the spacecraft’s O-rings—rubber seals that separated its rocket boosters—caused a fire to start that destabilized the boosters and spread up the rocket itself. The shuttle was moving faster than the speed of sound and quickly began to break apart. The disaster led to the deaths of all astronauts on board, including civilian Christa McAuliffe, a participant in NASA’s Teacher in Space project who was to teach classes and perform experiments while in space. The extended mission of the shuttle included deployment of satellites and the test of tools for studying astronomy and Halley’s Comet. The shuttle’s launch was not widely televised, but the explosion and breakup of the shuttle was visible to spectators on the ground. The launch itself, performed in 26 °F (−3 °C) weather, was predicted to encounter issues by members of the engineering team who knew of the dangers posed to O-rings by such low temperatures. Despite vocalizing these concerns, the mission continued as planned because NASA was against delaying the shuttle’s launch any more, as it had already been delayed multiple times. The disaster resulted in the temporary suspension of the space shuttle program and the creation of the Rogers Commission to determine the cause and fault of the disaster.</p>
            <h2>Apollo 12: Lightning Strikes and a Head Scrape</h2>
            <p>The second manned lunar expedition, a feat astronaut Charles Conrad called, “a small step for Neil [Armstrong], but…a long one for me,” was not without a few mishaps. As Apollo 12 was beginning to lift off on November 14, 1969, the top of the shuttle was hit by two different lightning strikes that had the potential to compromise the spacecraft and the mission. The first strike was even visible to the spectating audience, creating a stir and concern about the safety of the mission. But despite the scare, it was determined in a quick check of all the spacecraft’s systems that no damage was done to the vehicle, and it set off to the Moon just as planned. It was the return to Earth that caused a little more trouble. As the spacecraft “splashed down” in the ocean during its return to Earth, a strong wave hit the body of the craft, causing it to jostle and swing from its parachutes. This force toppled a 16-mm film camera from where it was secured into astronaut Alan Bean’s head, causing a 1-inch (2.5-cm) cut. Bean turned out A-OK though, as Conrad quickly served as medic and bandaged the wound.</p>
            <h2>STS-107: Space Shuttle Columbia Disaster</h2>
            <p>The disintegration of the space shuttle Columbia on February 1, 2003, as it reentered the atmosphere was another of the most traumatic accidents in the history of space expedition. The Columbia disaster was the second that occurred during NASA’s space shuttle program after the Challenger, also causing widespread sadness and concerns about the space programs. The accident was caused during liftoff by the breaking off of a piece of foam that was intended to absorb and insulate the fuel tank of the shuttle from heat and to stop ice from forming. The large piece of foam fell on the shuttle’s left wing and created a hole. Though NASA officials were aware of the damage, the severity of it was unclear because of the low-quality cameras used to observe the shuttle’s launch. Knowing that the foam regularly had fallen off of previous shuttles and had not caused critical damage, NASA officials believed there was nothing to worry about. But when the Columbia attempted reentry after its mission was complete, gases and smoke entered the left wing through the hole and caused the wing to break off, leading to the disintegration of the rest of the shuttle seven minutes from landing. The entire crew of six American astronauts and the first Israeli astronaut in space died in the accident. NASA’s space shuttle program was again suspended after this disaster. Despite the tragedy, an experiment performed during the expedition that studied the effects of weightlessness on the physiology of worms was recovered from the wreckage. The worms, left in a petri dish, were still alive, a symbol of the dedication of the Columbia crew and a monument to their efforts.</p>
            <h2>Apollo-Soyuz Test Project: Poisonous Gas Leak</h2>
            <p>The Apollo-Soyuz Test Project in July 1975 was a feat of both space travel and politics: it was the first joint U.S. and Soviet spaceflight and marked the end of the space race between the two countries. Bottle up all of the tension between these two superpowers, and there’s bound to be some mishap. Surprisingly, the mission itself went over almost flawlessly (until their returns). The two spacecraft—the American holding three astronauts and the Soviet two cosmonauts—met in orbit around the Earth and docked to each other, allowing the space explorers to travel between the vehicles. They exchanged pleasantries and gifts and executed some experiments, each group speaking in the other’s native language to smooth communication and blur the barriers between the two countries. After 44 hours they parted and, after a few more days, the two spacecraft began their descents to Earth. It was during reentry that a malfunction with the RCS, the reaction control system that controls altitude, caused poisonous nitrogen tetroxide to enter the cabin where the American Apollo astronauts were seated. Luckily, the cabin was ventilated once the spacecraft landed and none of the astronauts were fatally injured. They were rushed to a hospital and were found to have developed a form of chemically caused pneumonia, but all recovered within weeks.</p>
            <h2>Animals That Have Been To Space</h2>
            <p>•Monkeys and apes</p>
            <p>•Mice</p>
            <p>•Dogs</p>
            <p>•Spiders</p>
            <p>•Fish</p>
            <button className='button' onClick={() => navigate('/solar')}>Main Page</button>
        </div>
    )
}



export default Missions